version: '3.8'

services:
  web:
    build: .
    command: sh -c
      'python manage.py migrate
      && python manage.py collectstatic --clear --noinput
      && gunicorn --workers=6 --timeout 300 sibintek_rest.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - ./sibintek_rest/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
