version: '3.8'

services:
  web:
    build: .
    command: sh -c
      'python manage.py migrate
      && python manage.py collectstatic --clear --noinput
      && gunicorn --workers=4 --timeout 300 sibintek_rest.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  celery:
    build: .
    command: celery -A sibintek_rest worker --loglevel=info --concurrency 1 -E
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

volumes:
  static_volume:
  media_volume:
