# Generated by Django 5.0.1 on 2024-01-12 00:19

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat_image',
            field=models.ImageField(default='default_cat.jpg', upload_to=cats.models.path_to_rename),
        ),
    ]
