name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
    - run: echo "Value of MY_SECRET1 ${{secrets.DB_HOST}}"
    - name: Build and run containers
      run: |
        docker-compose -f docker-compose-dev.yml up -d --build
